---
driver:
  name: ec2
  instance_type: t2.micro
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: rhel-7.5

suites:
  - name: default
    run_list:
      - recipe[webserver_test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
